######################## default configuration ####################
# テスト用URL(公開する前にコメント戻す)
baseURL = "http://example.org/"
# 公開用URL
# baseURL = "https://nutfes.github.io/blog/"
canonifyurls = true
languageCode = "ja"
title = "NUTMEG | 長岡技術科学大学 技大祭実行委員会 情報局"
theme = "liva-hugo"
summaryLength = "2"
paginate = 6
disqusShortname = ""
publishDir = "docs"
[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Products"
  URL = "products"
  weight = 3

  [[menu.main]]
  name = "Members"
  URL = "members"
  weight = 4

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 3
  
  [[menu.footer]]
  name = "Members"
  URL = "members"
  weight =4

#################### default parameters ################################
[params]
logo = "images/NUTMEG-logo_all_color_horizontal.png"
home = "Home"
# Meta data
description = "長岡技術科学大学に所属する学生によって構成されたエンジニア団体、NUTMEGが普段の活動を発信するために始めたブログです!技大祭実行委員会の有志のみによって構成されており,普段は長岡技術大学のサークルの1つ,技大祭実行委員会として活動しています.技大祭をより効率的に,より楽しくできるように,技大祭に向けたプロダクトの開発や技育展への参加を行うなどやる気次第でとことん楽しめるそんな団体です.実行委員会の業務のDXはもちろん,外部での活動にも意欲的に参加しています."
author = "NUTMEG"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
# mobile = "仮0124857985320"
# email = "仮demo@email.com"
# location = "仮Dhaka, Bangladedsh"
# copyright
copyright = "&copy; NUTMEG 2022"
images = ["images/OGP.png"]




# レイアウト変更用css
customCSS = ["css/custom_post.css"]

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"
# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/nutfes_nutmeg"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/nutfes/?hl=ja"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/orgs/NUTFes"


###
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
