######################## default configuration ####################
# テスト用URL(公開する前にコメント戻す)
# baseURL = "http://example.org/"
# 公開用URL
baseURL = "https://nutfes.github.io/blog/"
canonifyurls = true
languageCode = "en-us"
title = "エンジニアブログ | 技大祭実行委員会 情報局"
theme = "liva-hugo"
summaryLength = "5"
paginate = 6
disqusShortname = ""
publishDir = "docs"

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "../../../static/css/custom_post.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2


  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2



#################### default parameters ################################
[params]
logo = "images/NUTMEG-logo_all_color_horizontal.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "NUTMEG"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
# mobile = "仮0124857985320"
# email = "仮demo@email.com"
# location = "仮Dhaka, Bangladedsh"
# copyright
copyright = "&copy; NUTMEG 2021"
# レイアウト変更用css
customCSS = ["/css/custom_post.css"]

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = false
expire_days = 2


############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/nut_fes?s=20"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/nutfes/?hl=ja"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/orgs/NUTFes"


###
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true